# Generated by Django 3.1.3 on 2020-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
